/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-16 00:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Date;
import java.util.ArrayList;
import book.model.dto.BookDTO;
import book.model.dao.BookDAO;

public final class list_005fsub_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("book.model.dao.BookDAO");
    _jspx_imports_classes.add("book.model.dto.BookDTO");
    _jspx_imports_classes.add("java.sql.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	BookDAO dao = new BookDAO();
	ArrayList<BookDTO> list = dao.getSelectAll();
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>도서목록</h2>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"80%\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>순번</th>\r\n");
      out.write("		<th>제목</th>\r\n");
      out.write("		<th>저자</th>\r\n");
      out.write("		<th>발행일</th>\r\n");
      out.write("		<th>분류</th>\r\n");
      out.write("		<th>등록일</th>\r\n");
      out.write("	</tr>\r\n");
	if(list.size() == 0) { 
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"6\" height=\"200px\" align=\"center\">등록된 내용이 없습니다..</td>\r\n");
      out.write("	</tr>\r\n");
	}

	int num = list.size();
	for(int i=0; i<list.size(); i++) {
		BookDTO dto = list.get(i);

      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>");
      out.print( num );
      out.write("</td>\r\n");
      out.write("		<td><a href=\"#\" onClick=\"move('view.jsp', '");
      out.print( dto.getNo() );
      out.write("');\">");
      out.print( dto.getSubject() );
      out.write("</a></td>\r\n");
      out.write("		<td>");
      out.print( dto.getAuthor() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( dto.getCreated() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( dto.getProfile() );
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( dto.getRegiDate() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");

		num--;
	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div style=\"border: 0px solid blue; width: 80%; margin: 10px, 0px;\" align=\"right\">\r\n");
      out.write("|\r\n");
      out.write("<a href=\"#\" onClick=\"move('list.jsp', '');\">목록</a>\r\n");
      out.write("|\r\n");
      out.write("<a href=\"#\" onClick=\"move('insert.jsp', '');\">등록</a>\r\n");
      out.write("|\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function move(value1, value2) {\r\n");
      out.write("	location.href = value1 + '?no=' + value2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
