/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-05 03:31:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shopMall;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import shopMall.model.dao.CartDAO;
import shopMall.model.dto.CartDTO;
import product.model.dao.ProductDAO;
import product.model.dto.ProductDTO;
import java.net.Inet4Address;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/shopMall/../_include/inc_header.jsp", Long.valueOf(1661305685415L));
    _jspx_dependants.put("/shopMall/_inc_top.jsp", Long.valueOf(1662347775069L));
    _jspx_dependants.put("/shopMall/../_include/inc_sessionChk.jsp", Long.valueOf(1661482669264L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("product.model.dao.ProductDAO");
    _jspx_imports_classes.add("shopMall.model.dao.CartDAO");
    _jspx_imports_classes.add("shopMall.model.dto.CartDTO");
    _jspx_imports_classes.add("product.model.dto.ProductDTO");
    _jspx_imports_classes.add("java.net.Inet4Address");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");

	String referer = request.getHeader("REFERER");
	String url = request.getRequestURL().toString();
	String uri = request.getRequestURI().toString();
	String path = request.getContextPath();
	String ip = Inet4Address.getLocalHost().getHostAddress();	// import java.net.Inet4Address;
/*	
	out.println("referer : " + referer + "<br>");
	out.println("url : " + url + "<br>");
	out.println("uri : " + uri + "<br>");
	out.println("ip : " + ip + "<br>");
*/	

	String menuGubun = request.getParameter("menuGubun");

	if(menuGubun == null || menuGubun.trim().equals("")) {
		menuGubun = "member_list";

/*		out.println("<script>");
		out.println("location.href='error.jsp?errorCode=001';");
		out.println("</script>");
*/
		return;
	}
	
	String[] imsiMenuGubunArray = menuGubun.split("_");
	String folderName = imsiMenuGubunArray[0];
	String fileName = imsiMenuGubunArray[1];
	String includePage = "../" + folderName + "/" + fileName + ".jsp";
		

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	int sessionNo = 0;
	String sessionId = "";
	String sessionName = "";
	String sessionGrade = "";
	String sessionEmail = "";
	
	if(session.getAttribute("sessionNo") != null) {
		sessionNo = (Integer) session.getAttribute("sessionNo");
		sessionId = (String) session.getAttribute("sessionId");
		sessionName = (String) session.getAttribute("sessionName");
		sessionGrade = (String) session.getAttribute("sessionGrade");
		sessionEmail = (String) session.getAttribute("sessionEmail");
	}
	

      out.write('\n');
      out.write('\n');

	String productCode_ = request.getParameter("productCode");
	int productCode = Integer.parseInt(productCode_);
	
	ProductDTO arguDto = new ProductDTO();
	arguDto.setProductCode(productCode);
	
	ProductDAO productDao = new ProductDAO();
	ProductDTO returnDto = productDao.getSelectOne(arguDto);

      out.write("\n");
      out.write("\n");
      out.write("<h2>쇼핑몰 상세보기</h2>\n");
      out.write("\n");
      out.write("<table border=\"1\" width=\"80%\">\n");
      out.write("	<tr>\n");
      out.write("		<td width=\"200\">상품번호</td>\n");
      out.write("		<td>");
      out.print(returnDto.getProductCode() );
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>상품이름</td>\n");
      out.write("		<td>");
      out.print(returnDto.getProductName() );
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>상품가격</td>\n");
      out.write("		<td>");
      out.print(returnDto.getProductPrice() );
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>제조사</td>\n");
      out.write("		<td>");
      out.print(returnDto.getVendorCode() );
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>등록일</td>\n");
      out.write("		<td>");
      out.print(returnDto.getRegiDate() );
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>상품이미지</td>\n");
      out.write("		<td>\n");
      out.write("			");

				String[] imsiArray01 = returnDto.getAttachInfo().split(",");
				for (int i=0; i<imsiArray01.length; i++) {
					String[] imsiArray02 = imsiArray01[i].split("[|]");
					if (imsiArray02[1].equals("-")) {
						out.println("이미지없음");
					} else {
						String imsiImgPath = "";
						imsiImgPath += request.getContextPath();
						imsiImgPath += "/attach";
						imsiImgPath += request.getContextPath();
						imsiImgPath += "/product/";
						imsiImgPath += imsiArray02[1];
						
						out.println("<img src='" + imsiImgPath + "' width='150' height='150'>");
					}
					out.println("<hr>");
				}
			
      out.write("\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td colspan=\"2\" style=\"padding: 20px;\">\n");
      out.write("			<select name=\"jumunSu\" id=\"jumunSu\">\n");
      out.write("			<option value=\"0\">-- 선택 --</option>\n");
      out.write("			\n");
      out.write("			");
 for (int i=1; i<=20; i++) { 
      out.write("\n");
      out.write("				<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\n");
      out.write("			");
 } 
      out.write("\n");
      out.write("			</select>\n");
      out.write("			&nbsp;\n");
      out.write("			<button type=\"button\" onClick=\"btnProc('saveCart');\">장바구니담기</button>\n");
      out.write("			<button type=\"button\" onClick=\"btnProc('gumae');\">바로구매</button>\n");
      out.write("			<button type=\"button\" onClick=\"btnProc('shopping');\">계속쇼핑</button>\n");
      out.write("			<button type=\"button\" onClick=\"btnProc('viewCart');\">장바구니보기</button>\n");
      out.write("		</td>\n");
      out.write("	</tr>	\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<form name=\"imsiForm\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<input type=\"hidden\" name=\"imsi\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function btnProc(value1) {\n");
      out.write("	if (value1 == 'saveCart') {\n");
      out.write("		if (confirm('장바구니에 담을까요?')) {\n");
      out.write("			//document.imsiForm.amount.value = document.getElementById(\"jumunSu\").value;\n");
      out.write("\n");
      out.write("			document.imsiForm.imsi.value = '");
      out.print(productCode );
      out.write("' + '|' + document.getElementById(\"jumunSu\").value;\n");
      out.write("				\n");
      out.write("			document.imsiForm.action = \"mainProc.jsp?menuGubun=shopMall_cartChugaProc\";\n");
      out.write("			document.imsiForm.method = \"post\";\n");
      out.write("			document.imsiForm.submit();\n");
      out.write("		}\n");
      out.write("	} else if (value1 == 'gumae') {\n");
      out.write("		alert('요기까지..');\n");
      out.write("	} else if (value1 == 'shopping') {\n");
      out.write("		location.href = 'main.jsp?menuGubun=shopMall_list';\n");
      out.write("	} else if (value1 == 'viewCart') {\n");
      out.write("		location.href = 'main.jsp?menuGubun=shopCart_list';\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
